apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: rv45tsug3-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:1eef7982ada0c7c20fd8fa72cec0948222d19e59@sha256:b23f1d72b3366fdf63bc46074a4609aa82f573d61f7dc377739dadead66f3db7
        name: container-image  
